# Generated by Django 5.0.9 on 2024-10-22 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="(Name + Schedule)"),
                ),
                (
                    "day1",
                    models.TextField(
                        blank=True, verbose_name="First Availability: (day/s: time)"
                    ),
                ),
                (
                    "day2",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Second Availability: (day/s: time)",
                    ),
                ),
                (
                    "day3",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Third Availability: (day/s: time)",
                    ),
                ),
                (
                    "classes",
                    models.TextField(blank=True, verbose_name="Classes: (list all)"),
                ),
                (
                    "about",
                    models.TextField(
                        blank=True, verbose_name="Description: (tell us about yourself)"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
